### ISSUE TITLE
感谢你的贡献，但是描述里有一句话我觉得有点问题

### ISSUE THREAD

**Issue by eeeeLeeee** [ScenicPatrick/CLF-CQPUT#1]
描述里提到

> 学校内网的资源共享站的资源上传权限，常年掌握在少数人的手里。

我认为：
1.学校内网是完全开放的，免费的，并没有对任何人做限制。
2.不知道你提到的资源共享站是哪一个？但是这些共享站都是由学生自费维护的
3.大多数资源共享站 应该是欢迎用户提供资源的，但是由于审核和管理的问题，无法直接给上传权限而已。

**Comment by NMID-CQUPT** [comment]
非常抱歉，这段时间在忙别的事，一直没关注仓库情况。这么晚才回复你，请见谅！
感谢指正，现在想来，我三年前浏览到的那个内网上的共享站可能就是某个同学自费维护的。
描述不当的地方已经修改，再次感谢！
祝好！
